SONGS = ["Ain't Superstitious",
         "A Little Light",
         "Maggies Farm",
         "Alabama Getaway",
         "Alice D. Millionaire",
         "Alhambra",
         "Alligator",
         "All Too Much",
         "All I Have To Do Is Dream",
         "Althea",
         "All Along The Watchtower",
         "And We Bid You Goodnight",
         "And We Bid You Goodnight Jam",
         "Are You Lonely For Me Baby?",
         "Attics Of My Life",
         "Around & Around",
         "Baba O'Riley",
         "Baby What You Want Me To Do",
         "Bad Moon Rising",
         "Ballad Of A Thin Man",
         "Barbed Wire Whipping Party",
         "Bass & Drums",
         "Bass Solo",
         "Banana Boat Song",
         "Banks Of The Ohio",
         "Barbara Allen",
         "Beat It On Down The Line",
         "Beautiful Jam",
         "Believe It Or Not",
         "Bertha",
         "Beat It On Down The Line",
         "Big Boss Man",
         "Big Railroad Blues",
         "Bob & Brent jam",
         "Bo Diddley-itis (?)",
         "Born Cross-Eyed",
         "Built To Last",
         "Big River",
         "Big Boy Pete",
         "Bird Song",
         "Blackbird",
         "Black Muddy River",
         "Black Peter",
         "Black Queen",
         "Black Throated Wind",
         "Blow Away",
         "Blues For Allah",
         "Blue Moon",
         "Blues Jam",
         "Bob Star",
         "Born On The Bayou",
         "Box Of Rain",
         "Bring Me My Shotgun",
         "Brother Esau",
         "Brokedown Palace",
         "Broken Arrow",
         "Brown Eyed Women",
         "Built To Last",
         "Bye Bye Love",
         "California Earthquake",
         "Can't Come Down",
         "Cardboard Cowboy",
         "Casey Jones",
         "Cassidy",
         "Cathy's Clown",
         "Candyman",
         "Caution",
         "Caution Jam",
         "CC Rider",
         "Chanting by Guyto Monks",
         "Checkin' Up",
         "Chimes Of Freedom",
         "China Cat Sunflower",
         "China Cat Sunflower Jam",
         "Chinatown Shuffle",
         "Chinese Bones",
         "Childhood's End",
         "Children Of The Eighties",
         "China Doll",
         "Clementine",
         "Cold Jordan",
         "Cold Rain & Snow",
         "Comes A Time",
         "Come Back Baby",
         "Corrina",
         "Cosmic Charlie",
         "Crazy Fingers",
         "Cream Puff War",
         "Cryptical Envelopment",
         "Cumberland Blues",
         "Dancin' In The Streets",
         "Dark Star",
         "Dark Star Jam",
         "Dark Hollow",
         "Days Between",
         "Day-O",
         "Day Job",
         "Day Tripper",
         "Deal",
         "Dead Man, Dead Man",
         "Death Don't Have No Mercy",
         "Death Letter Blues",
         "Deep Elem Blues",
         "Devil In A Blue Dress",
         "Desolation Row",
         "Dear Mr. Fantasy",
         "Dire Wolf",
         "Do Right Woman, Do Right Man",
         "Doin' That Rag",
         "Don't Ease",
         "Don't Need Love",
         "Don't Think Twice, It's Alright",
         "Down In The Bottom",
         "Do You Wanna Dance?",
         "Drink Up And Go Home",
         "Drummers' Chant",
         "Drums",
         "Dupree's Diamond Blues",
         "Early Morning Rain",
         "Easy Answers",
         "Easy To Love You",
         "Easy Wind",
         "Eighteen Children",
         "El Paso",
         "Empty Pages",
         "Equinox",
         "Estimated Prophet",
         "Eternity",
         "Every Time You Go Away",
         "Eyes Of The World",
         "Fair Chance To Know",
         "Far From Me",
         "Fever",
         "Foolish Heart",
         "Forever Young",
         "Foxy Lady Jam",
         "Friend Of The Devil",
         "From The Heart Of Me",
         "Frozen Logger",
         "Feedback",
         "Feel Like A Stranger",
         "Fire On The Mountain",
         "Flibberty Jib",
         "Franklin's Tower",
         "Frankie Lee and Judas Priest",
         "Games People Play",
         "Gathering Flowers For The Master's Bouquet",
         "Gentleman Start Your Engines",
         "Get Back",
         "Going Down The Road Feeling Bad",
         "Gimme Some Lovin'",
         "Good Time Blues",
         "Gloria",
         "Golden Road",
         "Good Golly Miss Molly",
         "Good Lovin'",
         "Good Lovin' Jam",
         "Good Morning Little Schoolgirl",
         "Goodnight Irene",
         "Good Times",
         "Good Vibrations",
         "Got My Mojo Workin'",
         "Gotta Serve Somebody",
         "Greatest Story",
         "Green Green Grass Of Home",
         "Green River",
         "Hamza Jam",
         "Handsome Cabin Boy",
         "Hand Jive",
         "Happiness Is Drumming",
         "Happy Birthday",
         "Hard To Handle",
         "Heads Up",
         "Heart Of Mine",
         "Heaven Help The Fool",
         "He's Gone",
         "Hell In A Bucket",
         "Help Me Rhonda",
         "Help On The Way",
         "Here Comes Sunshine",
         "He Was A Friend Of Mine",
         "Hey Bo Diddley",
         "Hey Jude",
         "Hey Pocky Way",
         "Hide Away",
         "Hi-Heeled Sneakers",
         "Highway 61",
         "High Time",
         "Hoochie Coochie Man",
         "How Long Blues",
         "How Sweet It Is",
         "Hully Gully",
         "(I Can't Get No) Satisfaction",
         "If I Had The World To Give",
         "If The Shoe Fits",
         "I Get Around",
         "I Just Want To Make Love To You",
         "I'm A Man",
         "It's All Over Now",
         "It's All Over Now, Baby Blue",
         "It Takes A Lot To Laugh, It Takes A Train To cry",
         "It Must Have Been The Roses",
         "I Don't Know You",
         "I Fought The Law",
         "I Hear A Voice Callin'",
         "I Know You Rider",
         "I Need A Miracle",
         "A Mind to Give Up Livin'",
         "I'll Be Your Baby Tonight",
         "I'll Go Crazy",
         "It's A Sin",
         "I Want To Tell You",
         "I Want You",
         "I Washed My Hands In Muddy Water",
         "I Will Take You Home",
         "Iko Iko",
         "I'm A King Bee",
         "I'm A Hog For You Baby",
         "It's A Man's World",
         "It Hurts Me Too",
         "I've Been All Around this World",
         "I've Just Seen A Face",
         "Jam",
         "Jack Straw",
         "Jack-A-Roe",
         "Joey",
         "John Brown",
         "John's Other",
         "Johnny B. Goode",
         "Just A Little Light",
         "Just Like Tom Thumb's Blues",
         "Kansas City",
         "Katie Mae",
         "KC Moan",
         "Keep On Growing",
         "Knockin' On Heaven's Door",
         "La Bamba",
         "Lady Di and I",
         "Ladt With A Fan",
         "Lazy Lightning",
         "Lazy River Road",
         "Let It Be Me",
         "Let It Grow",
         "Let It Rock",
         "Let Me In",
         "Let Me Sing Your Blues Away",
         "Let The Good Times Roll",
         "Let it Grow",
         "Liberty",
         "Little Red Rooster",
         "Little Sadie",
         "Little Bunny Foo-Foo",
         "Looks Like Rain",
         "Long Black Limousine",
         "Loose Lucy",
         "Love The One You're With",
         "Lost Sailor",
         "Lucifer's Eyes",
         "Lucy In The Sky With Diamonds",
         "Loser",
         "Louie Louie",
         "Masons Children",
         "Maybe You Know",
         "Mama Tried",
         "Man Of Peace",
         "Man Smart (Woman Smarter)",
         "Mathilda",
         "Me & My Uncle",
         "Me & Bobby McGee",
         "Meet Me At The Bottom",
         "Memphis Blues Again",
         "Merry-Go-Round Broke Down",
         "Mexicali Blues",
         "Mexican Hat Dance",
         "Midnight Hour",
         "Might As Well",
         "Mindbender",
         "Mind Left Body Jam",
         "Minglewood Blues",
         "Mission In The Rain",
         "Mississippi Half Step",
         "My Babe",
         "Mystery Train",
         "Mona",
         "Money Money",
         "Monkey and the Engineer",
         "Mountain Jam",
         "Mountains Of The Moon",
         "The Mighty Quinn",
         "Morning Dew",
         "Mr. Charlie",
         "Mr Tambourine Man",
         "My Baby Left Me",
         "Neighborhood Girls",
         "Never Trust A Woman",
         "Next Time You See Me",
         "New Minglewood Blues",
         "New Potato Caboose",
         "New Orleans",
         "New Speedway Boogie",
         "Nobody's Fault But Mine",
         "Nobody's Fault Jam",
         "Not Fade Away",
         "Not Fade Away Chant",
         "Ode For Billie Dean",
         "Okie From Muskogee",
         "Oh Babe It Ain't No Lie",
         "Oh Boy",
         "Ollin Agrageed",
         "Old, Old House",
         "Ol' Slewfoot",
         "One More Saturday Night",
         "Only A Fool",
         "On The Road Again",
         "Operator",
         "Parchman Farm",
         "Passenger",
         "Peggy-O",
         "Peggy Sue",
         "Picasso Moon",
         "Pigpen Rap",
         "Phil's Earthquake Space",
         "Playin' In The Band",
         "Playin' Jam",
         "Playin' Reprise",
         "Pride Of Cucamonga",
         "Prisoner Blues",
         "Promised Land",
         "Proud Mary",
         "Queen Jane Approximately",
         "Ramble On Rose",
         "Railroading The Great Divide",
         "Rain",
         "Rainy Day Women #12 & #35",
         "Reuben & Cherise",
         "Revolution",
         "Revolutionary Hamstrung Blues",
         "Riot In Cell Block #9",
         "Ripple",
         "Rollin' and Tumblin'",
         "Road Runner",
         "Rockin' Pneumonia",
         "Rosalie McFall",
         "Running Show Blues",
         "Run Rudolph Run",
         "Row Jimmy",
         "Saint Of Circumstance",
         "Samba In The Rain",
         "Searchin'",
         "Set Break",
         "Sage & Spirit",
         "Salt Lake City",
         "Sampson & Delilah",
         "Sawmill",
         "Seastones",
         "Second That Emotion",
         "Scarlet Begonias",
         "See That My Grave Is Kept Clean",
         "Shakedown Street",
         "She Belongs To Me",
         "She's Mine",
         "Shelter From The Storm",
         "Ship Of Fools",
         "Sick And Tired",
         "Silver Threads & Golden Needles",
         "Sittin' On Top Of The World",
         "Sidewalks Of New York",
         "Sing Me Back Home",
         "Simple Twist Of Fate",
         "Slipknot",
         "Something On Your Mind",
         "Space",
         "Spanish Jam",
         "Spoonful",
         "Slow Blues (unknown title)",
         "Slow R and B Instrumental",
         "Slow Train Coming",
         "Smokestack Lightning",
         "Smokestack Lightnin' Jam",
         "Smokestack/Spoonful jam",
         "So Many Roads",
         "Stagger Lee",
         "Stander On The Mountain",
         "Star Spangled Banner",
         "Stars & Stripes Forever",
         "Stealin'",
         "St. Stephen",
         "Standing On The Moon",
         "Stella Blue",
         "Stir It Up",
         "Stir It Up Jam",
         "Stronger Than Dirt",
         "Stuck Inside Of Mobile With The Memphis Blues Again",
         "Supplication",
         "Supplication Jam",
         "Sugar Magnolia",
         "Sugar Shack",
         "Sunrise",
         "Sunshine Daydream",
         "Sugaree",
         "Swing Low, Sweet Chariot",
         "Take It All Off",
         "Take You Home",
         "Take Me To The River",
         "Tangled Up In Blue",
         "Tastebud",
         "That Would be Something",
         "That'll Be The Day",
         "The Ballad Of Casey Jones",
         "The Main Ten",
         "The Main Ten Jam",
         "The Only Time Is Now",
         "Till The Morning Comes",
         "Teddy Bear's Picnic",
         "Tell Mama",
         "Tennessee Jed",
         "Terrapin Station",
         "Terrapin Reprise",
         "That's Alright Mama",
         "The Boxer",
         "The Eleven",
         "The Eleven Jam",
         "The Island",
         "The Last Time",
         "The Music Never Stopped",
         "The Race Is On",
         "The Other One",
         "The Other One Jam",
         "The Rub",
         "The Same Thing",
         "The Seven",
         "The Story Of A Brick",
         "The Stranger (Two Souls In Communion)",
         "The Things I Used To Do",
         "The Times They Are A Changin'",
         "The Wheel",
         "The Weight",
         "They Love Each Other",
         "This Time Forever",
         "Throwing Stones",
         "Tico Tico",
         "Tiger By The Tail",
         "To Lay Me Down",
         "Tom Dooley",
         "Tomorrow Is A Long Time",
         "Tomorrow Is Forever",
         "Tomorrow Never Knows",
         "Tom Thumb Blues",
         "Tons Of Steel",
         "Touch Of Gray",
         "Truckin'",
         "Turn On Your Love Light",
         "Twist & Shout",
         "Two Trains Running",
         "Uncle John's Band",
         "Uncle John's Band Reprise",
         "Uncle John's Band Jam",
         "Uncle Sam Blues",
         "U.S. Blues",
         "Unbroken Chain",
         "Valley Road",
         "Victim Or The Crime",
         "Viola Lee Blues",
         "Visions Of Johanna",
         "Wabash Cannonball",
         "Wake Me Shake Me",
         "Wake Up Little Susie",
         "Warriors Of The Sun",
         "Watching The River Flow",
         "Wave To The Wind",
         "Walkin' Blues",
         "Walking The Dog",
         "Wang Dang Doodle",
         "Watching The River Flow",
         "Wave That Flag",
         "Whatcha Gonna Do",
         "Way To Go Home",
         "Weather Report Suite Part 1",
         "Weather Report Suite Prelude",
         "Weather Report Suite",
         "We Bid You Good Night",
         "We Can Run But We Can't Hide",
         "Werewolves Of London",
         "West L.A. Fadeaway",
         "What's Become Of The Baby",
         "What's Going On?",
         "When Push Comes To Shove",
         "Where Have All The Heroes Gone",
         "Wharf Rat",
         "When I Paint My Masterpiece",
         "Why Don't We Do It In The Road",
         "Who Do You Love?",
         "Who's Lovin' You Tonight",
         "Wicked Messenger",
         "Winin' Boy Blues",
         "Wipe Out",
         "Workin' Man Blues",
         "Wow Wow Hey Hey",
         "Yellow Dog Story",
         "You Ain't Woman Enough",
         "You Don't Have To Ask",
         "You Know I Love You So (Wo Wow Hey Hey)",
         "You Lied & Cheated",
         "You See A Broken Heart",
         "You Won't Find Me",
         "Yonder's Wall",
         "Youngblood",
         "Your Love At Home",
         "You Win Again",
         "wrs prelude> wrs part 1",
         "Dear Prudence Jam",
         "Close Encounters Jam",
         "Dark Star Jam",
         "Cosmic Charlie Tease",
         "Phil & Keyboards Jam",
         "Take A Step Back",
         "Adams Family",
         "Hamza El-Din",
         "Ken Nordine's Flibberdy Jib",
         "Countdown to Midnight",
         "Ken Kesey Rap",
         "A Day At The Dentist",
         "Addams Family Tuning",
         "26 Miles Tuning",
         "Funiculi Funicula",
         "Don't Ease Me In",
         "Whatcha Gonna Do",
         "Good Lovin'"
]
